server:  
  port: 811
  #port: ${PORT:0}  

spring:
  application:
    name: crm
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: web
    service:
      name: crm
  datasource:
    url:      jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${mysql.service.database}
    username: ${mysql.service.username}
    password: ${mysql.service.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
    
  rabbitmq:
    host: barnacle.rmq.cloudamqp.com
    port: 5672
    username: nccsiuvr
    password: FEfDUd1TNNbe3rDWDaUgF5TgqVJM62iH
    virtual-host: nccsiuvr
mysql:
  service:
    port: 3306
    host: localhost
    database: crm
    username: root
    password: 1234
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #instance:
    #sinstance-id: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}      


logging:
  level:
    root: info
    mcp:
      cloudtrace: info