server:  
  port: 9091
spring:
  application:
    name: webhook 
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: web
    service:
      name: webhook-notify
  datasource:
    url:      jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${mysql.service.database}
    username: ${mysql.service.username}
    password: ${mysql.service.password}
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa: 
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
    
    
mysql:
  service:
    port: 3306
    host:     localhost
    database: webhook
    username: root
    password: 1234
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/